- name: install required packages
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: yes
    pkg: 
    - curl
    - wget
    - gnupg
    - sudo
    - iptables
    - tmux
    - keepalived
    - haproxy
