---
- hosts: all
  #strategy: free
  #serial: 5
  roles:
    #    - role: resolv.conf
    - role: authorized_keys
    - role: etc_hosts
    - role: check_network
    - role: install_packages
    - role: k8s_preparing
    - role: install_k8s
    - role: install_containerd

- hosts: control_plane
  roles:
    - role: create_balancer
