---
- name: install openresolv package
  become: yes
  ansible.builtin.apt:
    name: "openresolv"
    state: present
    update_cache: yes

- name: add dns server to resolve.conf
  become: yes
  ini_file:
    path: /etc/resolvconf.conf
    state: present
    no_extra_spaces: yes
    option: name_servers
    value: "{{ dns_server }}"
  notify:
    - update resolvconf

