---
- name: Install htop
  become: true
  ansible.builtin.apt:
    name: "htop"
    state: present
    update_cache: yes

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', 'public_keys/id_ed25519.pub') }}"
