- name: Add an Apt signing key to a specific keyring file
  become: true
  ansible.builtin.apt_key:
    url: https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key
    keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg

- name: somerepo | apt source
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /"
    state: present
    filename: kubernetes

    #- name: Add specified repository into sources list using specified filename
    #  become: true
    #  ansible.builtin.apt_repository:
    #    repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
    #    state: present
    #    filename: kubernetes

- name: install required packages
  become: true
  ansible.builtin.apt:
    state: present
    update_cache: yes
    pkg: 
    - kubeadm
    - kubectl
